# Generated by Django 5.0.1 on 2024-09-01 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crt_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sec',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], default='A', max_length=1),
        ),
        migrations.AddField(
            model_name='user',
            name='sem',
            field=models.IntegerField(choices=[(1, 'I'), (2, 'II'), (3, 'III'), (4, 'IV'), (5, 'V'), (6, 'VI'), (7, 'VII'), (8, 'VIII')], default='1'),
        ),
    ]
