# Generated by Django 5.0.1 on 2024-09-06 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crt_app', '0002_user_sec_user_sem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='approval',
            old_name='stu_email',
            new_name='user_email',
        ),
        migrations.RenameField(
            model_name='approval',
            old_name='stu_name',
            new_name='user_name',
        ),
        migrations.RenameField(
            model_name='lessonplan',
            old_name='topic',
            new_name='topic_list',
        ),
        migrations.RenameField(
            model_name='subject',
            old_name='user',
            new_name='faculty_id',
        ),
        migrations.RemoveField(
            model_name='lessonplan',
            name='faculty',
        ),
        migrations.RemoveField(
            model_name='lessonplan',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='dept',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='sem',
        ),
        migrations.AddField(
            model_name='lessonplan',
            name='name',
            field=models.CharField(default='testing', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lessonplan',
            name='subject_id',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='crt_app.subject'),
            preserve_default=False,
        ),
    ]
