# Generated by Django 5.0.1 on 2024-09-06 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crt_app', '0003_rename_stu_email_approval_user_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='faculty_id',
        ),
        migrations.AddField(
            model_name='subject',
            name='faculty_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crt_app.user'),
        ),
    ]
