# Generated by Django 5.0.1 on 2024-09-06 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crt_app', '0004_remove_subject_faculty_id_subject_faculty_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessonplan',
            name='topic_list',
        ),
        migrations.AddField(
            model_name='lessonplan',
            name='topic_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crt_app.topic'),
        ),
    ]
