# Generated by Django 5.0.1 on 2024-09-06 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crt_app', '0005_remove_lessonplan_topic_list_lessonplan_topic_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessonplan',
            name='topic_list',
        ),
        migrations.AddField(
            model_name='topic',
            name='LessonPlan_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crt_app.lessonplan'),
        ),
    ]
