# Generated by Django 5.0.1 on 2024-09-08 01:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crt_app', '0006_remove_lessonplan_topic_list_topic_lessonplan_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('branch', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='sec',
        ),
        migrations.RemoveField(
            model_name='user',
            name='sem',
        ),
        migrations.AddField(
            model_name='user',
            name='class_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crt_app.class'),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photos/'),
        ),
        migrations.AddField(
            model_name='class',
            name='clg_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crt_app.college'),
        ),
        migrations.AddField(
            model_name='user',
            name='clg_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crt_app.college'),
        ),
    ]
