# Generated by Django 5.0.1 on 2024-09-12 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crt_app', '0007_college_remove_user_sec_remove_user_sem_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='college',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='user',
            name='specialisation',
        ),
        migrations.AddField(
            model_name='class',
            name='year',
            field=models.IntegerField(choices=[(1, 'I'), (2, 'II'), (3, 'III'), (4, 'IV'), (5, 'V'), (6, 'VI'), (7, 'VII'), (8, 'VIII')], default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='dept',
            field=models.CharField(choices=[('CSE', 'CSE'), ('ECE', 'ECE'), ('EEE', 'EEE'), ('MECH', 'MECH'), ('CIVIL', 'CIVIL'), ('x', 'x')], max_length=10),
        ),
    ]
