# Generated by Django 5.0.1 on 2024-09-19 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crt_app', '0009_alter_class_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
