# Generated by Django 5.0.1 on 2024-09-19 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crt_app', '0010_alter_class_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approval',
            name='approval_type',
            field=models.CharField(choices=[('new_stu_account', 'New Student Account'), ('new_fac_account', 'New Faculty Account'), ('new_lessonplan_approval', 'New Lesson Plan Approval')], default='new_stu_account', max_length=50),
        ),
        migrations.AlterField(
            model_name='approval',
            name='roll_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
